title: "Ionut Iorgulescu - Software Developer"
description: ""
keywords:
  - software developer
  - oop
  - clean code
  - ddd
  - domain-driven design
  - php

author:
  name: "Ionut Iorgulescu"
  headline: "Software Developer"
  bio: |
    Bucharest based <span>software developer</span>. Constantly experimenting with new technologies and techniques.
    I am very passionate about <span>Domain-Driven Design</span>, <span>Object-oriented analysis and design</span>, <span>Clean Code</span>,
    <span>I like yo play with Front-End Frameworks,</span> to look for and find new ways to constantly improve my programming skills.
  interests:
    - Domain-Driven Design
    - OOP
    - Clean Code
    - PHP
    - NodeJS
    - React

social_networks:
  twitter: "IorgulescuIonut"
  github: "https://github.com/ionutiorgulescu"
  email: "ionut@iorgulescu.me"
  url: "" 
google_analytics:
  id: UA-166675002-1
  site: iorgulescu.me
